### ISSUE TITLE
TODO: should refuse to serialize a value of character length 12 but byte length of 13

### ISSUE THREAD

**Issue by tunsira** [justmoon/dassie#16]
TODO: should refuse to serialize a value of character length 12 but byte length of 13

_Originally posted by @sublimator in https://github.com/justmoon/dassie/pull/13#discussion_r1045178994_

**Comment by sublimator** [comment]
Is this still outstanding ? 
iirc this was addressed, but will take another look

**Comment by sublimator** [comment]
This /was/ fixed, and the issue can be closed
