### ISSUE TITLE
Peer happy gets the log

### ISSUE THREAD

**Issue by sublimator** [justmoon/dassie#21]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/525211/229980248-fa76faed-96b1-43d3-ba21-0fe6753717b1.png">

If you want to click away on the + you're slowed down a bit, as the new node buttons (which will navigate to the logging for the new node) will be placed under the cursor.

**Comment by justmoon** [comment]
Fixed since the recent dev UI overhaul.

**Comment by sublimator** [comment]
Nice:
![image](https://github.com/justmoon/dassie/assets/525211/468d2f69-d328-44a7-8cf2-fe7c41aaaf75)

Somewhat related. It's hard to copy/paste text from the logs. Comes out all:
```
rlimit=no_limit
1.065
debug
n1
das:node:accounting create accountpath=builtin/owner/spsplimit=no_limit
1.066
debug
n1
das:node:accounting create accountpath=builtin/owner/btplimit=no_limit
1.092
info
n1
das:node:http listening on https://n1.localhost:4001
1.110
warn
n1
```


![image](https://github.com/justmoon/dassie/assets/525211/348d68d0-66d0-472e-8d90-ab5bb18150d8)

From: 6ca1afbe87d3202e9185217e43a9e9d35984f344
